US16
aldaitzwild/Catch_up pull request #11
Opened 2021-04-16 09:35 UTC by Unikorn44

Corrected a minor bug

2021-04-16 09:37 UTC, aldaitzwild requested changes
Confilct with dev

2021-04-16 10:00 UTC, Unikorn44 commented
conflict resolved

2021-04-16 10:01 UTC, aldaitzwild approved these changes
OK

2021-04-16 10:01 UTC, merged

2021-04-19 09:49 UTC, Unikorn44 commented
Conflict resolved