Us69
aldaitzwild/Catch_up pull request #25
Opened 2021-04-19 19:57 UTC by LudovicRAVINET

report profile from sought profile display to contact form

2021-04-20 07:37 UTC, aldaitzwild requested changes

2021-04-20 07:37 UTC, aldaitzwild commented on src/Controller/ContactController.php
> +    }
No, you don't use the $_SESSION to pass parameters on the server side. 
Here, instead of a header, why not render "Contact/contactForm.html.twig" with the params $profileId and $profilePseudo.

2021-04-20 07:37 UTC, aldaitzwild commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/contactForm.html.twig', ['session' => $_SESSION]);
You should never pass the session to a view.

2021-04-20 13:32 UTC, LudovicRAVINET commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/contactForm.html.twig', ['session' => $_SESSION]);
ok, so I put the $_SESSION in an other variable that I pass in render.

2021-04-21 08:17 UTC, aldaitzwild approved these changes
Yes ! Perfect.

2021-04-21 08:17 UTC, merged