Us34
aldaitzwild/Catch_up pull request #29
Opened 2021-04-21 15:29 UTC by Unikorn44

Avatar creation enabled

2021-04-21 15:41 UTC, Unikorn44 commented
Lines corrected

2021-04-21 15:47 UTC, Unikorn44 commented
Code corrected, libe 24 & 25

2021-04-22 06:55 UTC, aldaitzwild requested changes
FILE: src/Controller/AvatarsController.php
----------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
 24 | ERROR | [x] Opening parenthesis of a multi-line function call
    |       |     must be the last content on the line
 25 | ERROR | [x] Multi-line function call not indented correctly;
    |       |     expected 12 spaces but found 8
 26 | ERROR | [x] Multi-line function call not indented correctly;
    |       |     expected 12 spaces but found 8
 27 | ERROR | [x] Closing parenthesis of a multi-line function call
    |       |     must be on a line by itself
 34 | ERROR | [x] Whitespace found at end of line
----------------------------------------------------------------------
PHPCBF CAN FIX THE 5 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

2021-04-22 09:43 UTC, Unikorn44 reviewed
Chenges approved, added new random function

2021-04-22 11:21 UTC, aldaitzwild requested changes
No ! There still are quality issues : 

/home/runner/work/Catch_up/Catch_up/src/Controller/AvatarController.php:13	The variable $stringAléatoire is not named in camelCase.
/home/runner/work/Catch_up/Catch_up/src/Controller/AvatarController.php:13	The variable $stringAléatoire is not named in camelCase.
/home/runner/work/Catch_up/Catch_up/src/Controller/AvatarController.php:32	Avoid variables with short names like $bg. Configured minimum length is 3.


$stringAléatoire --> not accent allowed in a var name

2021-04-22 15:30 UTC, aldaitzwild requested changes

2021-04-22 15:30 UTC, aldaitzwild commented on src/Controller/AvatarController.php
> +/*session_start();*/
No dead code !

2021-04-23 07:35 UTC, aldaitzwild requested changes
Conflict with dev : 

Conflicting files
src/View/Profiles/profile.html.twig

2021-04-23 07:48 UTC, Unikorn44 commented
Code modified as requested

2021-04-23 09:58 UTC, Unikorn44 commented
I HATE AVAST !
Conflicts resolved

2021-04-23 10:16 UTC, aldaitzwild approved these changes

2021-04-23 10:16 UTC, merged