Us01 3 4
aldaitzwild/Catch_up pull request #31
Opened 2021-04-21 19:34 UTC by LudovicRAVINET

add index links and move contents under navbar to prepare friday demo

2021-04-22 09:21 UTC, aldaitzwild requested changes

2021-04-22 09:21 UTC, aldaitzwild commented on src/View/Home/index.html.twig
> +    <!--<button id="show_popup">Show popup</button>-->
No dead code !

2021-04-22 10:36 UTC, LudovicRAVINET commented on src/View/Home/index.html.twig
> +    <!--<button id="show_popup">Show popup</button>-->
ok

2021-04-22 11:19 UTC, aldaitzwild requested changes
Conflict with dev :

Conflicting files
src/View/SoughtProfile/soughtProfile.html.twig

2021-04-22 15:28 UTC, aldaitzwild requested changes

2021-04-22 15:28 UTC, aldaitzwild commented on src/View/SoughtProfile/soughtProfile.html.twig
> +<div class="cadre">
This div is not closed

2021-04-22 16:20 UTC, LudovicRAVINET commented on src/View/SoughtProfile/soughtProfile.html.twig
> +<div class="cadre">
ok I forgot it :(

2021-04-23 07:34 UTC, aldaitzwild approved these changes

2021-04-23 07:34 UTC, merged