Us15
aldaitzwild/Catch_up pull request #5
Opened 2021-04-14 15:39 UTC by Unikorn44

New PR, with dev this time

2021-04-15 06:58 UTC, aldaitzwild requested changes
You need to merge with dev and get what Ludovic sent into your branch

2021-04-15 08:12 UTC, aldaitzwild requested changes

2021-04-15 08:12 UTC, aldaitzwild commented on public/assets/css/style.css
> +>>>>>>> dev
You have a conflict !

2021-04-15 08:12 UTC, aldaitzwild commented on src/View/SoughtProfile/soughtProfile.html.twig
>                      }, 1000);
Yeah two more conflicts !

2021-04-15 09:46 UTC, Unikorn44 commented on src/View/SoughtProfile/soughtProfile.html.twig
>                      }, 1000);
Conflicts resolved

2021-04-15 09:48 UTC, aldaitzwild requested changes
Quality control failed : 
FILE: src/Controller/ConnectController.php
----------------------------------------------------------------------
FOUND 21 ERRORS AND 1 WARNING AFFECTING 21 LINES
----------------------------------------------------------------------
  1 | WARNING | [ ] A file should declare new symbols (classes,
    |         |     functions, constants, etc.) and cause no other
    |         |     side effects, or it should execute logic with
    |         |     side effects, but should not do both. The first
    |         |     symbol is defined on line 8 and the first side
    |         |     effect is on line 5.
  3 | ERROR   | [x] Header blocks must be separated by a single blank
    |         |     line
  4 | ERROR   | [x] Header blocks must be separated by a single blank
    |         |     line
 17 | ERROR   | [x] Expected 1 space(s) after closing parenthesis;
    |         |     found " /*vérification remplissage champs*/\n   
    |         |         "
 20 | ERROR   | [x] Space before opening parenthesis of function call
    |         |     prohibited
 21 | ERROR   | [x] Space before opening parenthesis of function call
    |         |     prohibited
 22 | ERROR   | [x] Whitespace found at end of line
 24 | ERROR   | [x] Whitespace found at end of line
 25 | ERROR   | [x] Whitespace found at end of line
 27 | ERROR   | [x] Expected 1 space(s) after IF keyword; 0 found
 27 | ERROR   | [x] Expected 1 space(s) after closing parenthesis;
    |         |     found newline
 29 | ERROR   | [x] Whitespace found at end of line
 30 | ERROR   | [x] Expected 1 space after closing brace; newline
    |         |     found
 31 | ERROR   | [x] Expected 1 space(s) after ELSE keyword; newline
    |         |     found
 33 | ERROR   | [x] Expected 1 space(s) after closing parenthesis;
    |         |     found " /*comparaison des passwords*/\n          
    |         |          "
 34 | ERROR   | [x] Whitespace found at end of line
 36 | ERROR   | [x] Whitespace found at end of line
 38 | ERROR   | [x] Expected 1 space after closing brace; newline
    |         |     found
 39 | ERROR   | [x] Expected 1 space(s) after ELSE keyword; newline
    |         |     found
 43 | ERROR   | [x] Whitespace found at end of line
 46 | ERROR   | [x] Function closing brace must go on the next line
    |         |     following the body; found 1 blank lines before
    |         |     brace
 47 | ERROR   | [x] Expected 1 blank line at end of file; 2 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 21 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: src/Model/ConnectManager.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 37 | WARNING | Line exceeds 120 characters; contains 126 characters
----------------------------------------------------------------------

2021-04-16 06:13 UTC, Unikorn44 commented
Bugs corrected, code cleaned

2021-04-16 06:51 UTC, aldaitzwild requested changes
Code quality : 

FILE: src/Model/ConnectManager.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 37 | WARNING | Line exceeds 120 characters; contains 126 characters
----------------------------------------------------------------------

2021-04-16 07:32 UTC, Unikorn44 commented
Corrected some lines to pass the quality test

2021-04-16 08:28 UTC, closed without merging