Avatar and userId are affiliated
aldaitzwild/Catch_up pull request #50
Opened 2021-04-27 13:56 UTC by Unikorn44

2021-04-27 13:59 UTC, aldaitzwild requested changes

2021-04-27 13:59 UTC, aldaitzwild commented on src/Controller/AvatarController.php
> +    //var_dump($string);
No dead code !

2021-04-27 13:59 UTC, aldaitzwild commented on src/View/Profiles/profile.html.twig
> +
More dead code !

2021-04-27 16:07 UTC, Unikorn44 commented
Dead code removed

2021-04-28 06:40 UTC, Unikorn44 commented
Checked

2021-04-28 06:54 UTC, aldaitzwild requested changes
You have conflict with Dev : 

Conflicting files
public/assets/images/avatars/avatar3.png
src/View/Profiles/profile.html.twig

2021-04-28 12:09 UTC, Unikorn44 commented
Conflicts resolved

2021-04-28 14:48 UTC, aldaitzwild requested changes

2021-04-28 14:48 UTC, aldaitzwild commented on src/Controller/AvatarController.php
> +        //$_SESSION ['userId'] = 3;
No dead code !

2021-04-28 14:48 UTC, aldaitzwild commented on src/View/Profiles/profile.html.twig
> +<div class="cadre">
Warning div not closed

2021-04-29 06:59 UTC, aldaitzwild requested changes
Conflicts with dev : 

Conflicting files
public/assets/css/style.css

2021-04-29 08:49 UTC, aldaitzwild requested changes
Still Dead code ...

2021-04-29 11:24 UTC, aldaitzwild requested changes
It's always the last zombie that kill everyone at the end : 

AvatarController.php => line 12  : Dead Code !

2021-04-29 12:48 UTC, Unikorn44 commented
No mOaR deAd cOd3 ?

2021-04-29 12:50 UTC, aldaitzwild approved these changes

2021-04-29 12:50 UTC, merged