Added some details to profile
aldaitzwild/Catch_up pull request #75
Opened 2021-05-04 12:06 UTC by Unikorn44

Added some explainations to how to choose your pictures

2021-05-04 13:05 UTC, aldaitzwild requested changes

2021-05-04 13:05 UTC, aldaitzwild commented on src/View/Profiles/profile.html.twig
> +						</br>
What is that abomination ??? Please be more nice with HTML.

2021-05-05 14:09 UTC, Unikorn44 commented on src/View/Profiles/profile.html.twig
> +						</br>
done

2021-05-05 16:32 UTC, aldaitzwild approved these changes

2021-05-05 16:32 UTC, merged